### ISSUE TITLE
Limit leaderboard to active players.

### ISSUE THREAD

**Issue by HumbleBroski** [NathanJCochran/just-too-easy#6]
When someone creates an account, they are given a base score that puts them at the top of the leaderboard. This interferes with the ranking of people who are actively playing.
Possible solutions for this include:
- Limiting leaderboard to players that have played at least 10 games.
- Limiting leaderboard to players that have played a game in the past month.
- Both of the above.
- Introducing a score penalty for inactivity.

**Comment by NathanJCochran** [comment]
Fixed by #8
