### ISSUE TITLE
Active Games does not function as expected.

### ISSUE THREAD

**Issue by HumbleBroski** [NathanJCochran/just-too-easy#7]
The "Games" section of the app lists games under an "Active Games" title. These games are dated all the way back to 2014, so unless someone has been playing a single foosball game for three years, these games need to be cleared out, and this list needs to be properly updated.

**Comment by NathanJCochran** [comment]
They are "active" because they were never completed. The goal was to add functionality so that you could pick a game back up, in case you had to stop early for some reason.
